=== isafdezpe/SEW/XML/Ejercicio-2/Tarea-1/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (tipo,transporte,fecha?,hora?,duracion,agencia,descripcion,personas,lugar,direccion,coordenadas,referencia+,recomendacion,hitos)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT transporte (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT personas (#PCDATA)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT coordenadas (longitud,latitud,altitud)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT hitos (hito+)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT hito (descripcion-hito,coordenadas-hito,distancia,galeria)>
<!ELEMENT descripcion-hito (#PCDATA)>
<!ELEMENT coordenadas-hito (longitud-hito,latitud-hito,altitud-hito)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT galeria (fotografia+,video*)>
<!ELEMENT longitud-hito (#PCDATA)>
<!ELEMENT latitud-hito (#PCDATA)>
<!ELEMENT altitud-hito (#PCDATA)>
<!ELEMENT fotografia (#PCDATA)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST ruta nombre CDATA #REQUIRED>
<!ATTLIST referencia ref-number CDATA #IMPLIED enlace CDATA #REQUIRED>
<!ATTLIST hito nombre CDATA #REQUIRED>
<!ATTLIST distancia unidades CDATA #REQUIRED>
<!ATTLIST fotografia archivo CDATA #REQUIRED>
<!ATTLIST video archivo CDATA #REQUIRED>

=== isafdezpe/SEW/XML/Ejercicio-2/Tarea-1/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<?xml-stylesheet type="text/css" href="rutas.css"?>
<?xml-stylesheet type="text/xsl" href="rutas.xsl"?>

<rutas>
    <ruta nombre="Ruta por Oviedo">
        <tipo>Monumentos</tipo>
        <transporte>A pie</transporte>
        <fecha>2018-11-02</fecha>
        <hora>12:00</hora>
        <duracion>PT2H</duracion>
        <agencia>Turismo de Oviedo</agencia>
        <descripcion>Recorrido visitando los monumentos más conocidos de Oviedo</descripcion>
        <personas>Jóvenes y adultos</personas>
        <lugar>Oviedo</lugar>
        <direccion>Plaza de la catedral</direccion>
        <coordenadas>
            <longitud>43º21'44''N</longitud>
            <latitud>-5º50'39''W</latitud> 
            <altitud>232m</altitud>
        </coordenadas>
        <referencia ref-number="1" enlace="http://el.tesorodeoviedo.es/index.php?title=Plaza_de_Alfonso_II">Plaza de la catedral</referencia>
        <referencia ref-number="2" enlace="https://es.wikipedia.org/wiki/La_Regenta_(escultura)">Escultura La Regenta</referencia>
        <referencia ref-number="3" enlace="https://es.wikipedia.org/wiki/La_lechera_(escultura)">Escultura La Lechera</referencia>
        <recomendacion>8</recomendacion>
        <hitos>
            <hito nombre="La Lechera">
                <descripcion-hito>Esculura homenaje a las mujeres que trabajaron como leceras hasta mediados del silo XX.</descripcion-hito>
                <coordenadas-hito>
                    <longitud-hito>43º21'38''N</longitud-hito>
                    <latitud-hito>-5º50'38''W</latitud-hito> 
                    <altitud-hito>233m</altitud-hito>
                </coordenadas-hito>
                <distancia unidades="metros">300</distancia>
                <galeria>
                    <fotografia archivo="multimedia/Oviedo_aldeana_sculpture.jpg">Fotografía de la escultura</fotografia>
                    <fotografia archivo="multimedia/trascorrales.jpg">Fotografía de la plaza</fotografia>
                </galeria>
            </hito>
            <hito nombre="Vendedoras del Fontán">
                <descripcion-hito>Representa a las mujeres que venían a Oviedo para vender cerámica.</descripcion-hito>
                <coordenadas-hito>
                    <longitud-hito>43º21'34''N</longitud-hito>
                    <latitud-hito>-5º50'45''W</latitud-hito> 
                    <altitud-hito>232m</altitud-hito>
                </coordenadas-hito>
                <distancia unidades="metros">280</distancia>
                <galeria>
                    <fotografia archivo="multimedia/Vendedoras_del_Fontan.jpg">Fotografía de la escultura</fotografia>
                </galeria>
            </hito>
            <hito nombre="¡Adiós, cordera!">
                <descripcion-hito>Representa el cuento de Alas Clarín del mismo nombre que la escultura.</descripcion-hito>
                <coordenadas-hito>
                    <longitud-hito>43º21'42''N</longitud-hito>
                    <latitud-hito>-5º51'12''W</latitud-hito> 
                    <altitud-hito>241m</altitud-hito>
                </coordenadas-hito>
                <distancia unidades="metros">850</distancia>
                <galeria>
                    <fotografia archivo="multimedia/Adios_Cordera.jpg">Fotografía de la escultura</fotografia>
                </galeria>
            </hito>
        </hitos>
    </ruta>
    <ruta nombre="Ruta por la costa">
        <tipo>Paisajística</tipo>
        <transporte>Mixta a pie y bus</transporte>
        <fecha>2019-05-05</fecha>
        <hora>10:00</hora>
        <duracion>PT6H</duracion>
        <agencia>Turismo de Asturias</agencia>
        <descripcion>Recorrido visitando lugares de la costa Asturiana</descripcion>
        <personas>Jóvenes y adultos</personas>
        <lugar>Luarca</lugar>
        <direccion>Faro de Luarca</direccion>
        <coordenadas>
            <longitud>43º32'58''N</longitud>
            <latitud>-6º31'57''W</latitud> 
            <altitud>17m</altitud>
        </coordenadas>
        <referencia ref-number="1" enlace="https://www.turismoasturias.es/descubre/costa">Descubre la costa asturiana</referencia>
        <referencia ref-number="2" enlace="https://www.turismoasturias.es/descubre/costa/villas-marineras/marinera-luarca">Luarca</referencia>
        <referencia ref-number="3" enlace="https://www.turismoasturias.es/descubre/costa/villas-marineras/marinera-cudillero">Cudillero</referencia>
        <referencia ref-number="4" enlace="https://www.turismoasturias.es/descubre/costa/villas-marineras/marinera-lastres">Lastres</referencia>
        <recomendacion>10</recomendacion>
        <hitos>
            <hito nombre="Cudillero">
                <descripcion-hito>Con un relevante puerto pesquero, es un pueblo con mucho turismo.</descripcion-hito>
                <coordenadas-hito>
                    <longitud-hito>43º33'36''N</longitud-hito>
                    <latitud-hito>-6º08'55''W</latitud-hito> 
                    <altitud-hito>49m</altitud-hito>
                </coordenadas-hito>
                <distancia unidades="kilometros">39.4</distancia>
                <galeria>
                    <fotografia archivo="multimedia/cudillero.jpg">Puerto de Cudillero</fotografia>
                    <fotografia archivo="multimedia/Cudillero-Faro-y-acantilado.jpg">Faro de Cudillero</fotografia>
                </galeria>
            </hito>
            <hito nombre="Luanco">
                <descripcion-hito>Se encuentra a poca distancia del Cabo Peñas y su turismo se ha desarrollado superando en importancia a la pesca.</descripcion-hito>
                <coordenadas-hito>
                    <longitud-hito>43º36'49''N</longitud-hito>
                    <latitud-hito>-5º47'34''W</latitud-hito> 
                    <altitud-hito>4m</altitud-hito>
                </coordenadas-hito>
                <distancia unidades="kilometros">47.2</distancia>
                <galeria>
                    <fotografia archivo="multimedia/260px-Luanco_-_10.jpg">Casco histórico de Luanco</fotografia>
                    <fotografia archivo="multimedia/210px-Torre_del_reloj_(Luanco).jpg">Torre del reloj</fotografia>
                </galeria>
            </hito>
            <hito nombre="Lastres">
                <descripcion-hito>Fue el escenario de la serie televisiva "Doctor Mateo"</descripcion-hito>
                <coordenadas-hito>
                    <longitud-hito>43º30'50''N</longitud-hito>
                    <latitud-hito>-5º16'13''W</latitud-hito> 
                    <altitud-hito>58m</altitud-hito>
                </coordenadas-hito>
                <distancia unidades="kilometros">60.4</distancia>
                <galeria>
                    <fotografia archivo="multimedia/Lastres,_Asturias.jpg">Vista desde el mar</fotografia>
                </galeria>
            </hito>
        </hitos>
    </ruta>
    <ruta nombre="Ruta de la sidra por Gijón">
        <tipo>Gastronómica</tipo>
        <transporte>Mixta a pie y bus</transporte>
        <fecha>2018-11-03</fecha>
        <hora>18:30</hora>
        <duracion>PT3H</duracion>
        <agencia>Turismo Gijón</agencia>
        <descripcion>Recorrido por llagares de Gijón</descripcion>
        <personas>Adultos</personas>
        <lugar>Gijón</lugar>
        <direccion>Llagar Sidra Trabanco</direccion>
        <coordenadas>
            <longitud>43º28'13''N</longitud>
            <latitud>-5º38'45''W</latitud> 
            <altitud>153m</altitud>
        </coordenadas>
        <referencia ref-number="1" enlace="http://www.gijon.info/directorios/show/3418-llagar-sidra-trabanco">Llagar Sidra Trabanco</referencia>
        <referencia ref-number="2" enlace="http://www.gijon.info/directorios/show/9482-llagar-bernueces">Llagar Bernueces</referencia>
        <referencia ref-number="3" enlace="http://www.gijon.info/directorios/show/3415-llagar-sidra-pinera">Llagar Sidra Piñera</referencia>
        <referencia ref-number="4" enlace="http://www.gijon.info/directorios/show/3398-sidra-acebal">Sidra Acebal</referencia>
        <recomendacion>8</recomendacion>
        <hitos>
            <hito nombre="Llagar Bernueces">
                <descripcion-hito>Llagar Bernueces es uno de los llagares más antiguos de Asturias. Con unos orígenes que datan de 1881, se trata de uno de esos enclaves únicos donde la tradición cultural y gastronómica se encuentra impregnada en cada detalle, en cada rincón.</descripcion-hito>
                <coordenadas-hito>
                    <longitud-hito>43º30'35''N</longitud-hito>
                    <latitud-hito>-5º37'32''W</latitud-hito> 
                    <altitud-hito>58m</altitud-hito>
                </coordenadas-hito>
                <distancia unidades="kilometros">7.1</distancia>
                <galeria>
                    <fotografia archivo="multimedia/c130x108_v1_bernueces.jpg"/>
                </galeria>
            </hito>
            <hito nombre="Llagar Sidra Piñera">
                <descripcion-hito>Sidra Piñera es una empresa asturiana, de cáracter totalmente familiar, que desde hace más de 50 años ofrece a sus clientes su sidra, fabricada de manera totalmente artesanal.</descripcion-hito>
                <coordenadas-hito>
                    <longitud-hito>43º30'06''N</longitud-hito>
                    <latitud-hito>-5º36'15''W</latitud-hito> 
                    <altitud-hito>74m</altitud-hito>
                </coordenadas-hito>
                <distancia unidades="kilometros">2.2</distancia>
                <galeria>
                    <fotografia archivo="multimedia/c130x108_v1_pipineraera.jpg"/>
                </galeria>
            </hito>
            <hito nombre="Sidra Acebal">
                <descripcion-hito>En el llagar de Sidra Acebal podrás ver cómo se elabora la sidra tradicional asturiana.</descripcion-hito>
                <coordenadas-hito>
